app/barong/config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  use_doorkeeper
  mount UserApi::Base, at: '/api'
  mount ManagementAPI::V1::Base, at: '/management_api'

  devise_for :accounts, controllers: { sessions: :sessions,
                                       confirmations: :confirmations }
  devise_scope :account do
    match 'accounts/sign_in/confirm', to: 'sessions#confirm', via: %i[get post]
  end

  root to: 'index#index', as: :index

  post 'phones/verification', to: 'phones#verify'

  get  'security',            to: 'security#enable'
  post 'security/confirm',    to: 'security#confirm'

  get 'health/alive', to: 'health#alive'
  get 'health/ready', to: 'health#ready'

  resources :phones,    only: %i[new create]
  resources :profiles,  only: %i[new create]
  resources :documents, only: %i[new create]

  namespace :admin do
    get '/', to: 'accounts#index', as: :accounts
    resources :accounts, except: %i[new create] do
      post :disable_2fa, on: :member

      resources :labels, except: %i[index show]
    end
    resources :websites
    resources :profiles, only: %i[edit update] do
      put :document_label, on: :member
    end
  end
end

app/barong/app/controllers/security_controller.rb
# frozen_string_literal: true

class SecurityController < ApplicationController
  before_action :check_otp_enabled
  before_action :check_vault_availability

  def enable
    @otp = Vault::TOTP.create(current_account.uid, current_account.email)
    Rails.logger.debug { "Vault TOTP data #{@otp.inspect}" }
    @otp_secret = Vault::TOTP.otp_secret(@otp)
    Rails.logger.debug { "TOTP secret #{@otp_secret.inspect}" }
  end

  def confirm
    if Vault::TOTP.validate?(current_account.uid, params[:otp])
      status = current_account.update(otp_enabled: true)
      return redirect_to index_path, notice: '2FA is enabled' if status
      redirect_to security_path, alert: current_account.errors.full_messages.to_sentence
    else
      redirect_to security_path, alert: 'Code is invalid'
    end
  end

private

  def check_vault_availability
    return if Vault::TOTP.server_available?

    redirect_to index_path, alert: '2FA is disabled'
  end

  def check_otp_enabled
    return unless current_account.otp_enabled
    redirect_to(index_path, alert: '2FA has been enabled for this account')
  end
end

app/barong/app/views/security/enable.html.erb
<div class="row justify-content-center">
  <div class="container-fluid box-shadow mx-3">
    <div class="mb-3">
      <h2 class="title font-weight-bold">Get your Google Auth code</h2>
    </div>
  </div>

  <div class="container-fluid mx-3 px-5 py-4 d-flex flex-column align-items-center">
    <img alt="QR Code" src="data:image/png;base64,<%= @otp.data[:barcode] %>" />
    <input class="form-control text-center" value="<%= @otp_secret %>" disabled />
    <a class="visible-xs" href="<%= @otp.data[:url] %>">Open in Google Authenticator</a>

    <div class="container-fluid mx-3 px-5 py-4 d-flex flex-column align-items-center">
      <%= form_tag(security_confirm_path) do %>
        <div id="otp-code" class="form-group">
          <div class="row">
            <%= label_tag :otp, '6-digit Google Authenticator code' %>
            <%= text_field_tag :otp, '', autocomplete: 'off', class: 'px-1 form-control form-control-lg underlined', required: true, maxlength: 6, size: 6, pattern: '\d{6}', placeholder: 'XXXXXX' %>
          </div>
        </div>
        <div class="row mt-4 d-flex justify-content-between">
          <%= submit_tag 'Submit', class: 'btn btn-success', data: { confirm: 'Do you agree? If you lost your device you will need to verify your access' } %>
        </div>
      <% end %>
    </div>
  </div>
</div>